version: "3"
services:
  spring-boot-oauth2-auth-server:
    container_name: spring-boot-oauth2-auth-server
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DEPLOY_ENV: "test-ci-cd"
    image: "spring-boot-oauth2-auth-server:latest"
    restart: unless-stopped
    env_file: spring-boot-oauth2-auth-server/ci-cd-test.env
    volumes:
      - /home/bitto/certs:/certs
    network_mode: "bridge"
    ports:
      - "5020:5020"