name: Docker Build & Deploy

on:
  push:
    branches: ["main"]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repositoty
        uses: actions/checkout@v3

      - name: Log into registry registry.gitlab.com
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: bittokazi
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

      - name: Build and Push Java Backend Image
        run: cd ./spring-boot-oauth2-auth-server && docker build . --file ./Dockerfile --tag registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/backend:latest && docker push registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/backend:latest

      - name: Build and Push Angular Frontend Image
        run: cd ./auth-kit-frontend && docker build . --file ./prod.Dockerfile --tag registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/frontend:latest && docker push registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/frontend:latest

  deploy-trigger:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy Trigger
        uses: fjogeleit/http-request-action@v1.14.2
        with:
          url: https://infra.bittokazi.com/gitlab-deploy/spring-boot-oauth2-multi-tenant-auth-server
          method: "POST"
          username: "n/a"
          password: "n/a"
          customHeaders: '{"Content-Type": "application/json", "X-Gitlab-Token": "9a567f38-5313-4b60-9e45-3a61a7ecf9dc"}'
          data: '{"ref": "refs/heads/main"}'
